kind: Service
apiVersion: v1
metadata:
  name: spark-master-2-1-0
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      nodePort: 31210
      name: http
  type: NodePort
  selector:
    component: spark-master-2-1-0